### ISSUE TITLE
Image 0.4.1 cassée sous Debian

### ISSUE THREAD

**Issue by jaubin** [Zenika/Formation--Framework#102]
L'image 0.4.1 docker du framework formation est cassée sous Debian stable, tandis que la latest fonctionne. Serait-il possible :
- Soit de mettre à jour cette image
- Soit de mettre à jour les formations ? (mais dans ce cas on perd quelque part l'intérêt du framework unifié)

**Comment by hgwood** [comment]
Peux-tu décrire plus précisément le problème ?

**Comment by jaubin** [comment]
Je lance une formation qui utilise cette image et j'obtiens : 
"Couldn't get a file descriptor referring to the console"

Semblerait que ce soit un problème qui se produite avec Node.js version 0.10 mais pas la version 0.12. Toujours est-il qu'avec l'image latest ça démrre.

Autrement dit la formation git qui utilise l'image latest fonctionne, celle sur angularjs ne fonctionne pas.

**Comment by ldez** [comment]
Problème connu, il faut monter de version en 0.4.5.

**Comment by ldez** [comment]
la formation AngularJS utilise la version `latest`

**Comment by ggerbaud** [comment]
Je clos celui-ci, il faut monter de version
