### ISSUE TITLE
https vs SSH

### ISSUE THREAD

**Issue by ldez** [Zenika/Formation--Framework#32]
NPM ne marche plus avec les dépendances du type "git+https:"

J'utilise npm 2.9.0 et node 0.12.0

Pour faire fonctionner npm je suis obligé de changer les urls en "git+ssh:"

**Comment by jlandure** [comment]
on peut clore cette issue maintenant que le repo est public ?

**Comment by ldez** [comment]
C'est vraiment la solution qui a été choisit ? je pensais que c'était une blague.

**Comment by jlandure** [comment]
En même temps, il n'y a rien de confidentiel dans ce repo :)
cf les pb rencontrés dernièrement sur le slack #web

**Comment by ldez** [comment]
du coup il va falloir modifier les formations qui avaient corrigé l'url en SSH

**Comment by ggerbaud** [comment]
logiquement ça fonctionne toujours en ssh
le seul point un peu négatif mais pas très grave c'est que ça a cassé les liens avec les forks, donc faut rajouter le remote dans les forks
