### ISSUE TITLE
Ajouter une page de garde pour le site hebergé

### ISSUE THREAD

**Issue by jlandure** [Zenika/Formation--Framework#57]
Le déploiement continue des formations permet d'avoir tout en ligne.
Nous allons créer une page de garde pour avoir accès:
* slides en ligne
* PDF (slides et cahier d'exercices)
* lien vers le github
* lien vers la description de la formation sur zenika.com

Le but de cette feature est de générer cette page à partir d'info dans le package.json de la formation.

**Comment by ggerbaud** [comment]
C'est done. Thanks @jlandure
