### ISSUE TITLE
Upgrade 0.3.x -> 0.4.0

### ISSUE THREAD

**Issue by cAhmad** [Zenika/Formation--Framework#67]
Serait-il possible d'indiquer (pourquoi pas dans le [CHANGELOG](https://github.com/Zenika/Formation--Framework/blob/master/CHANGELOG.md)) que lors de l'upgrade du framwork il faut rajouter dans le `package.json` de la formation le bloc :
```json
"config": {
    "deploy": {
      "name": "zen-formation-replace-me"
    }
  }
```
?

**Comment by ggerbaud** [comment]
C'est indiqué ici : https://github.com/Zenika/Formation--Modele#intégration-continue

Mais c'est peut-être pas assez visible

**Comment by cAhmad** [comment]
Si si c'est lisible, mais lorsque j'ai monté de version le framework, j'ai juste regardé le changelog pour voir s'il n'y avait pas d'impact.

J'aurais dû aussi voir que le répo [Formation--Modele](https://github.com/Zenika/Formation--Modele) avait été mis à jour.

**Comment by ggerbaud** [comment]
je clos donc
