### ISSUE TITLE
Régression et Listes

### ISSUE THREAD

**Issue by ldez** [Zenika/Formation--Framework#69]
Les puces sur plusieurs niveaux n'ont plus d'indentation.

Reveal 3.1 / Fwk 4.1 -> FAIL
Reveal 3.0 / Fwk 4.0 -> OK

**Comment by ggerbaud** [comment]
Précision
Reveal 3.1 / Fwk 4.1 -> FAIL
Reveal **2.6** / Fwk 4.0 -> OK

**Comment by ldez** [comment]
Le style est bien mieux avec 3.1 mais les problèmes d'indentation tue la feature.
Je n'ai pas pris le temps de regarder pourquoi mais c'est surement un de nos fichiers styles qui pollue.

**Comment by ggerbaud** [comment]
Je pense aussi que nos css ne sont plus adaptées à cette version.

**Comment by gquintana** [comment]
Est-ce qu'il y a un contournement?

En l'état ce problème rend le Framework 0.4.1 inutilisable AMHA

**Comment by gquintana** [comment]
Contournement rapide pour l'indentation des listes:

```
.reveal ol, .reveal ul {
    padding: 0 1em;
}
```

**Comment by ggerbaud** [comment]
La version (release) 0.4.1 est restée en reveal 2.6...
Les versions 0.5.x seront en reveal 3

**Comment by ggerbaud** [comment]
Plus d'actualité
