### ISSUE TITLE
Nouveaux types de slides

### ISSUE THREAD

**Issue by ldez** [Zenika/Formation--Framework#70]
On lutte trop avec Reveal pour avoir un rendu cohérent suivant nos besoins.

Il faudrait pouvoir avoir plusieurs "types" de slides afin de gérer les problèmes.

Les problèmes :
- Espace entre les lignes trop grandes si ce n'est pas une liste à puces
- les bloc de codes ne se disposent pas correctement suivant les situations.
- etc

Il serait bon de faire un inventaire des problèmes et des pratiques custom pour trouver une solution.

**Comment by ldez** [comment]
pour exemple regarder la formation React : https://github.com/Zenika/formation-react/pull/37

**Comment by ggerbaud** [comment]
Désolé mais je comprends pas, même avec l'issue de React...
Quelque chose m'échappe

**Comment by ldez** [comment]
regarde bien les bloc de code :+1:
@ncuillery n'utilise pas les bloc mais juste des lignes avec des simples  backstick uniquement pour avoir un rendu correct.
Il y a des $nbsp; uniquement pour que le code pleine page ressemble à quelque chose.

C'est des problèmes récurrents, @gquintana pourra te le confirmer.

**Comment by ncuillery** [comment]
Je vais forker et prendre des screenshots. Ca sera plus simple.

**Comment by hgwood** [comment]
@ldez Tu peux pointer sur une ligne en particulier s'il te plait ? Je n'arrive pas à trouver un exemple de ce que tu décrit.

**Comment by ldez** [comment]
@ncuillery a récrit son historique de PR, pas bien... Du coup on ne voit plus rien

**Comment by ncuillery** [comment]
Voir issues susmentionnées.

Concernant la rigidité des blocs de code, c'est à mon sens moins prioritaire que les 2 autres

**Comment by ggerbaud** [comment]
Cette issue n'a donc plus lieu d'être car remplacée par #71 #72 et #73
