### ISSUE TITLE
Changement sur les Alert

### ISSUE THREAD

**Issue by gquintana** [Zenika/Formation--Framework#74]
Avec le framework 0.4.1

```
## Alert

<!-- .element: class="alert alert-danger" -->
Attention danger!

<!-- .element: class="alert alert-info" -->
Message d'information

Blabla
```

donne 

![alert](https://cloud.githubusercontent.com/assets/755587/9441195/ec0285ea-4a74-11e5-92b7-080324598a98.png)

Visiblement, il faut mettre les .element après le paragraphe et non pas avant:
```
## Alert

Attention danger!
<!-- .element: class="alert alert-danger" -->

Message d'information
<!-- .element: class="alert alert-info" -->

Blabla
```

**Comment by vdemeester** [comment]
Méfiance également avec `<!-- element` :

```markdown
*Continuous Integration* : Fast, automated feedback on the correctness of your application every time there is a change to code, — *Neal Ford*
<!-- .element class="alert alert-success" style="text-align: center" -->
```
Les attributs de cet éléments s'applique uniquement à "l'élément" le plus proche.. donc le `<strong>Neal Ford</strong>`

Du coup pour avoir un rendu correct :

```markdown
*Continuous Integration* : Fast, automated feedback on the correctness of your application every time there is a change to code, — *Neal Ford*

<!-- .element class="alert alert-success" style="text-align: center" -->
```

Vu qu'avant on mettait le `<!-- .element`` au dessus le soucis ne se posait pas..

**Comment by ggerbaud** [comment]
Attention changement

Version 0.4.1 (release) => reveal 2.6, theme css reste OK

Css à corriger pour le passage a reveal 3 en release 0.5.0

**Comment by ggerbaud** [comment]
plus d'actualité
