### ISSUE TITLE
Taille des images

### ISSUE THREAD

**Issue by MaBeuLux88** [Zenika/Formation--Framework#75]
Visiblement, il y a une régression au niveau de la taille des images avec la dernière version v4.1 du framework.
exemples : 
https://master-dot-zen-formation-angularjs.appspot.com/slides.html#/1/13
https://master-dot-zen-formation-angularjs.appspot.com/slides.html#/1/16

![out](https://cloud.githubusercontent.com/assets/7153911/9509020/7b7920ca-4c5b-11e5-91f9-6b91d61f4d28.png)
![douglas_depasse](https://cloud.githubusercontent.com/assets/7153911/9509039/a442ca60-4c5b-11e5-8944-932b4031af58.png)

**Comment by ggerbaud** [comment]
Pour info, la version (au sens release) 0.4.1 est sur reveal 2.6 et ne pose pas ce problème.
Le css du theme devra etre corrigé pour le passage a reveal 3 en version 0.5.0

**Comment by ggerbaud** [comment]
plus d'actualité
