### ISSUE TITLE
NPM3

### ISSUE THREAD

**Issue by ldez** [Zenika/Formation--Framework#77]
NPM3 est sortie de beta.

Le framework ne marche pas avec NPM3.

```
>> Tasks directory "c:\sources\zenika\formations\formation-tdd\node_modules\zenika-formation-framework/node_modules/grunt-sed/tasks" not found.
>> Tasks directory "c:\sources\zenika\formations\formation-tdd\node_modules\zenika-formation-framework/node_modules/grunt-contrib-connect/tasks" not found.
>> Tasks directory "c:\sources\zenika\formations\formation-tdd\node_modules\zenika-formation-framework/node_modules/grunt-contrib-watch/tasks" not found.
>> Tasks directory "c:\sources\zenika\formations\formation-tdd\node_modules\zenika-formation-framework/node_modules/grunt-contrib-clean/tasks" not found.
>> Tasks directory "c:\sources\zenika\formations\formation-tdd\node_modules\zenika-formation-framework/node_modules/grunt-contrib-copy/tasks" not found.
>> Tasks directory "c:\sources\zenika\formations\formation-tdd\node_modules\zenika-formation-framework/node_modules/grunt-filerev/tasks" not found.
>> Tasks directory "c:\sources\zenika\formations\formation-tdd\node_modules\zenika-formation-framework/node_modules/grunt-filerev-replace/tasks" not found.
```

**Comment by ldez** [comment]
@hgwood il me semblait que tu avais corrigé de problème dans #64, j'ai loupé un truc ?

**Comment by ldez** [comment]
Je viens de voir que la PR de @hgwood n'est pas dans l'arbre de commit il y a eut un problème.

**Comment by ggerbaud** [comment]
Le code de la #64 ne fonctionnait finalement pas avec npm 2, donc ça a été reverté

**Comment by ldez** [comment]
Pour information `gulp` as été ajouté pour ceux qui ont npm3 en attendant. (depuis la version 0.4.4)

Il suffit de lancer avec la commande `gulp`.
Pour l'instant uniquement la lecture des slides est disponible.

**Comment by ggerbaud** [comment]
Quel est le statut du support de npm 3 ?

**Comment by ldez** [comment]
pour l'instant uniquement lancement des slides.

**Comment by hgwood** [comment]
Du coup avec #115 on est bon non ? Je pense que oui donc je ferme mais n'hésitez pas à rouvrir si j'ai oublié quelque chose.
