### ISSUE TITLE
Gestion du dépôt avec un GitFlow

### ISSUE THREAD

**Issue by ldez** [Zenika/Formation--Framework#79]
Passage à un GitFlow afin de mieux gérer les versions.

Pour résumé :
- master : version en cours  (prod)
- develop : version en cours de dev
- release : branche dédié aux release

Ressources :
- https://fr.atlassian.com/git/tutorials/comparing-workflows/gitflow-workflow
- http://danielkummer.github.io/git-flow-cheatsheet/
- https://datasift.github.io/gitflow/GitFlowForGitHub.html
- https://datasift.github.io/gitflow/IntroducingGitFlow.html

**Comment by ggerbaud** [comment]
Alors oui ça pourrait être mieux géré mais là c'est overkill.
Il n'est pas prévu pour le moment de maintenir plusieurs versions en //

**Comment by ldez** [comment]
la version 0.5.0 va être une rupture qui va impacter les formations, dans un premier temps avoir 2 version en parallèle me parait justifié pour ne avoir à corriger toutes les formations d'un coup.

**Comment by hgwood** [comment]
Un master avec des tags n'est pas suffisant ?

**Comment by ldez** [comment]
Actuellement, le problème c'est que la version en cours de dev (master) est considéré comme 'latest' et cela rend l'utilisation des images dockers impossible avec le bon rendu.

**Comment by hgwood** [comment]
OK donc avec une git flow, 'latest' désignerait une version stable. Mais on aurait toujours le problème de #81, non ? On ça n'a rien à voir ?

**Comment by ldez** [comment]
en fait quelque soit la solution l'objectif c'est de pouvoir avoir une 0.4.2 (Reveal 2 et Node 3) et une 0.5.0 (Reveal 3 et Node 3)

**Comment by jlandure** [comment]
_Hypothèse : nous parlons du fmk--formation ^^_
Le gitflow me parait effectivement overkill...
Je ferai simple : 
- latest = 0.5.0 = reveal3/node3 = la version qui a le plus d'avenir 
- 0.4.2 = reveal2/node3

**Comment by ldez** [comment]
- 0.4.2 = reveal2/node2 (avec option node3 partiel)

Je ne suis pas sur pour le `latest` car la 0.5.0 n'est pas prête, je dirais simplement qu'il faut 2 branches :
- master
- develop

**Comment by jlandure** [comment]
`master` et `release` comme sur les projets de formation, ça serait pas mal non ? 
du coup, release = latest côté image docker.

**Comment by ldez** [comment]
:+1:
