### ISSUE TITLE
Faire une version 0.4.2

### ISSUE THREAD

**Issue by ldez** [Zenika/Formation--Framework#80]
Faire une version 0.4.2 pour le support de NPM3.

**Comment by ggerbaud** [comment]
Par contre ce sera en 0.5.0 et avec Reveal 3

**Comment by ldez** [comment]
Bof j'aimerais bien avoir une version qui marche maintenant sinon je suis bloqué.

**Comment by ggerbaud** [comment]
bloqué ?
Moi je préfère que les contributions se fassent sur la correction de notre css, sinon ce ne sera jamais fait

**Comment by ldez** [comment]
oui bloqué parce je ne peux pas avoir 2 versions d'installée sur mon système (oui j'utilise Windows...)

**Comment by hgwood** [comment]
Tu peux avoir npm 2 et 3 sur ton poste je pense.

Si on imagine que tu veux garder npm 3 par défaut, tu peux installer npm 2 comme ceci :
- tu te mets dans un dossier où tu veux installer npm 2
- tu fais `npm i npm@2`
- tu copie `node_modules/npm/bin/npm.cmd` dans `.` puis tu le renommes `npm2.cmd`
- tu ajoutes le dossier courant à ton PATH

**Comment by ldez** [comment]
Le problème c'est le "cache" et de dossier "prefix".
Un autre problème : lancer une formation et travailler avec Node n'est pas possible.

Dans tout les cas c'est justement ce que je veux éviter : avoir à manipuler mon path dès que je fais quelque chose.

**Comment by ggerbaud** [comment]
Si je comprends bien (j'en suis pas sur). Si on merge cette PR, chez toi ça marche (et chez d'autres qui sont déjà passés à npm3). Mais chez tout ceux qui sont sur npm2, ça ne marchera plus. J'ai bon ?

Cela m’embête car l'adoption du framework se fait déjà dans la douleur pour certains, si on force tout ceux qui ont installé npm2 juste pour la formation à passer à npm3 ça va être compliqué.

Ne peut on vraiment pas trouver une solution qui fonctionnerait à la fois en npm2 et 3 ?

**Comment by ldez** [comment]
Tu as bien compris et je comprends tout à fait le problème d'adoption.
En fait maintenant npm 3 est la version qui s'installe par défaut quand tu fais `npm install -g npm`.
npm 2 est passé en mode LTS.

il est possible de faire un truc horrible : référencer les CSS et JS dans les 2 versions et donc avoir plein de 404. Il faudrait tester avec NPM 2 pour voir s'il n'y a pas d'autre effet de bord.

**Comment by hgwood** [comment]
Ça pourrait effectivement faire l'affaire ! Bonne idée.

**Comment by ggerbaud** [comment]
@ldez tu refais une PR (ou update la précédente) ?

Tant que tu y es, penses tu qu'il soit possible de mettre un message dans la console pour ceux qui sont en npm 2 et qui leur dit de se mettre a npm3 (et comment faire) ?

**Comment by ldez** [comment]
ok je update la précédente.
Je vais regarder pour le message.

Est-ce que tu peut créer une branche pour faire une 0.4.2 (Reveal 2) ?

**Comment by ggerbaud** [comment]
Je vais bourriner sur l'historique pour mettre l'actuel master dans une branche 0.5.x, le master réaligné pour le moment sur 0.4.1 et faire une branche dev

Du coup tu feras ta PR sur Dev, qui deviendra
