### ISSUE TITLE
Génération de PDF vide sur la CI

### ISSUE THREAD

**Issue by ldez** [Zenika/Formation--Framework#87]
Je viens de voir que les pdf des toutes formations en version 0.4.4 sont vides.

**Comment by ldez** [comment]
les slides marchent parfaitement c'est uniquement les PDF...

**Comment by ldez** [comment]
j'ai trouvé c'est un problème avec PhantomJS :
```
ReferenceError: Can't find variable: Promise

  http://localhost:8000/reveal/run.js:138
```

**Comment by ggerbaud** [comment]
Etrange, celui là, une version de qqch est mal fixée, car rien n'a été monté de version coté JS

**Comment by ldez** [comment]
c'est à cause des modifications que j'ai faites dans la 0.4.2 sur le fichier `run.js`.
Tout marche bien dans les navigateurs mais je n'avais pas testé la génération des slides en PDF via PhantomJS.
