### ISSUE TITLE
Améliorer la documentation

### ISSUE THREAD

**Issue by ggerbaud** [Zenika/Formation--Framework#99]
Améliorer la documentation afin qu'elle apporte toutes les réponse a quelqu'un qui découvrirait le fwk pour la première fois.

Partir éventuellement d'un cobaye qui loguerait toutes les difficultés qu'il rencontre lors de la découverte du framework

**Comment by jlandure** [comment]
Le but de cette issue est 
1) d'améliorer le contenu du fmk--modele 
2) d'améliorer le README
3) de créer un wiki sur fmk--formation ?

**Comment by hgwood** [comment]
Je ne suis pas sûr qu'il soit utile de laisser cette issue ouverte, car elle est très générale et ne comporte pas d'objectif tangible. Je vais la fermer.
